const User = require('../models/User');
const PartnerCommission = require('../models/PartnerCommission');
const SystemSettings = require('../models/SystemSettings');
const catchAsync = require('../utils/catchAsync');
const AppError = require('../utils/AppError');
const crypto = require('crypto');

// Helper to get or create system settings
const getSystemSettings = async () => {
  let settings = await SystemSettings.findOne({ key: 'global_settings' });
  if (!settings) {
    settings = await SystemSettings.create({ key: 'global_settings', defaultPartnerCommissionRate: 20 });
  }
  return settings;
};

// Helper to generate 100% unique partner code
const generateUniquePartnerCode = async () => {
  let isUnique = false;
  let code = '';
  while (!isUnique) {
    code = 'SP-' + crypto.randomBytes(4).toString('hex').toUpperCase();
    const existing = await User.exists({ partnerCode: code });
    if (!existing) isUnique = true;
  }
  return code;
};

// --- SALES PARTNER ENDPOINTS ---

// GET /api/partner/dashboard
exports.getPartnerDashboard = catchAsync(async (req, res, next) => {
  const user = req.user;

  // Ensure partner code exists
  if (!user.partnerCode) {
    user.partnerCode = await generateUniquePartnerCode();
    await user.save({ validateBeforeSave: false });
  }

  // Get referred users
  const referredUsers = await User.find({ referredByPartner: user._id })
    .select('name email createdAt subscription')
    .sort('-createdAt');

  // Auto-sync missing commissions strictly for captured payment records
  const Payment = require('../models/Payment');
  const settings = await getSystemSettings();
  const rate = user.partnerCommissionRate || settings.defaultPartnerCommissionRate || 20;

  for (const refUser of referredUsers) {
    const capturedPayments = await Payment.find({ user: refUser._id, status: 'captured' });
    for (const pmt of capturedPayments) {
      const existing = await PartnerCommission.findOne({
        partner: user._id,
        referredUser: refUser._id,
        $or: [
          { payment: pmt._id },
          { paymentAmount: (pmt.amount / 100), notes: { $regex: pmt.plan } }
        ]
      });
      if (!existing && pmt.amount > 0) {
        const priceInRupees = pmt.amount / 100;
        const commAmount = Math.round((priceInRupees * rate) / 100);

        if (commAmount > 0) {
          await PartnerCommission.create({
            partner: user._id,
            referredUser: refUser._id,
            payment: pmt._id,
            paymentAmount: priceInRupees,
            commissionAmount: commAmount,
            commissionRate: rate,
            status: 'APPROVED',
            notes: `Auto-synced referral commission for captured payment plan: ${pmt.plan}`
          });
        }
      }
    }
  }

  // Get commissions summary
  const commissions = await PartnerCommission.find({ partner: user._id });

  const totalEarned = commissions
    .filter(c => c.status === 'APPROVED' || c.status === 'PAID')
    .reduce((sum, c) => sum + c.commissionAmount, 0);

  const pendingPayout = commissions
    .filter(c => c.status === 'APPROVED')
    .reduce((sum, c) => sum + c.commissionAmount, 0);

  const paidOut = commissions
    .filter(c => c.status === 'PAID')
    .reduce((sum, c) => sum + c.commissionAmount, 0);

  res.status(200).json({
    status: 'success',
    data: {
      partnerCode: user.partnerCode,
      commissionRate: user.partnerCommissionRate || settings.defaultPartnerCommissionRate,
      commissionType: settings.commissionType,
      minPayoutThreshold: settings.minPayoutThreshold,
      totalReferrals: referredUsers.length,
      totalEarned,
      pendingPayout,
      paidOut,
      referredUsers,
      recentCommissions: commissions.slice(0, 10)
    }
  });
});

// GET /api/partner/payouts
exports.getPartnerPayouts = catchAsync(async (req, res, next) => {
  const commissions = await PartnerCommission.find({ partner: req.user._id })
    .populate('referredUser', 'name email')
    .sort('-createdAt');

  res.status(200).json({
    status: 'success',
    data: { commissions }
  });
});

// --- ADMIN ENDPOINTS ---

// GET /api/partner/admin/partners
exports.getAllPartners = catchAsync(async (req, res, next) => {
  const partners = await User.find({ role: 'sales_partner' })
    .select('name email role partnerCode partnerCommissionRate createdAt')
    .sort('-createdAt');

  const Payment = require('../models/Payment');

  // Populate total earnings and sales revenue for each partner
  const partnerData = await Promise.all(partners.map(async (p) => {
    const referredUsers = await User.find({ referredByPartner: p._id }).select('_id');
    const referredUserIds = referredUsers.map(u => u._id);

    // Calculate total revenue generated by referred users
    const capturedPayments = await Payment.find({ user: { $in: referredUserIds }, status: 'captured' });
    const totalRevenueGenerated = capturedPayments.reduce((sum, pmt) => sum + ((pmt.amount || 0) / 100), 0);

    const commissions = await PartnerCommission.find({ partner: p._id });
    
    const totalEarned = commissions
      .filter(c => c.status === 'APPROVED' || c.status === 'PAID')
      .reduce((sum, c) => sum + c.commissionAmount, 0);

    const pendingPayout = commissions
      .filter(c => c.status === 'APPROVED')
      .reduce((sum, c) => sum + c.commissionAmount, 0);

    const paidOut = commissions
      .filter(c => c.status === 'PAID')
      .reduce((sum, c) => sum + c.commissionAmount, 0);

    return {
      ...p.toObject(),
      referralsCount: referredUsers.length,
      totalRevenueGenerated,
      totalEarned,
      pendingPayout,
      paidOut
    };
  }));

  res.status(200).json({
    status: 'success',
    data: { partners: partnerData }
  });
});

// GET /api/partner/admin/partner-users/:partnerId
exports.getPartnerReferredUsers = catchAsync(async (req, res, next) => {
  const { partnerId } = req.params;

  const partner = await User.findById(partnerId).select('name email role partnerCode partnerCommissionRate createdAt');
  if (!partner) return next(new AppError('Sales Partner not found', 404));

  const Payment = require('../models/Payment');
  const referredUsers = await User.find({ referredByPartner: partnerId })
    .select('name email createdAt subscription role')
    .sort('-createdAt');

  const userSummaries = await Promise.all(referredUsers.map(async (refUser) => {
    // Get captured payments for this user
    const payments = await Payment.find({ user: refUser._id, status: 'captured' })
      .select('plan amount razorpayPaymentId createdAt billingPeriod')
      .sort('-createdAt');

    const totalPaidAmount = payments.reduce((sum, p) => sum + ((p.amount || 0) / 100), 0);

    // Get commissions generated by this user for the partner
    const commissions = await PartnerCommission.find({ partner: partnerId, referredUser: refUser._id })
      .sort('-createdAt');

    const totalCommissionEarned = commissions
      .filter(c => c.status === 'APPROVED' || c.status === 'PAID')
      .reduce((sum, c) => sum + c.commissionAmount, 0);

    return {
      ...refUser.toObject(),
      paymentsCount: payments.length,
      totalPaidAmount,
      totalCommissionEarned,
      payments,
      commissions
    };
  }));

  const totalRevenueGenerated = userSummaries.reduce((sum, u) => sum + u.totalPaidAmount, 0);
  const totalCommissionsEarned = userSummaries.reduce((sum, u) => sum + u.totalCommissionEarned, 0);

  res.status(200).json({
    status: 'success',
    data: {
      partner,
      totalReferredUsers: referredUsers.length,
      totalRevenueGenerated,
      totalCommissionsEarned,
      referredUsers: userSummaries
    }
  });
});

// POST /api/partner/admin/assign-role
exports.assignPartnerRole = catchAsync(async (req, res, next) => {
  const { userId, role, customCommissionRate } = req.body;

  const user = await User.findById(userId);
  if (!user) return next(new AppError('User not found', 404));

  if (role) user.role = role;
  if (customCommissionRate !== undefined) user.partnerCommissionRate = customCommissionRate;

  if (user.role === 'sales_partner' && !user.partnerCode) {
    user.partnerCode = await generateUniquePartnerCode();
  }

  await user.save({ validateBeforeSave: false });

  res.status(200).json({
    status: 'success',
    message: `User ${user.email} updated successfully.`,
    data: { user }
  });
});

// GET /api/partner/admin/settings
exports.getAdminSettings = catchAsync(async (req, res, next) => {
  const settings = await getSystemSettings();
  res.status(200).json({ status: 'success', data: { settings } });
});

// PATCH /api/partner/admin/settings
exports.updateAdminSettings = catchAsync(async (req, res, next) => {
  const { defaultPartnerCommissionRate, commissionType, minPayoutThreshold } = req.body;

  let settings = await SystemSettings.findOne({ key: 'global_settings' });
  if (!settings) {
    settings = new SystemSettings({ key: 'global_settings' });
  }

  if (defaultPartnerCommissionRate !== undefined) settings.defaultPartnerCommissionRate = defaultPartnerCommissionRate;
  if (commissionType) settings.commissionType = commissionType;
  if (minPayoutThreshold !== undefined) settings.minPayoutThreshold = minPayoutThreshold;

  await settings.save();

  res.status(200).json({
    status: 'success',
    message: 'Global partner settings updated.',
    data: { settings }
  });
});

// POST /api/partner/admin/process-payout
exports.processPayout = catchAsync(async (req, res, next) => {
  const { partnerId, payoutTxnId, notes } = req.body;

  if (!partnerId) return next(new AppError('Partner ID is required', 400));

  const pendingCommissions = await PartnerCommission.find({ partner: partnerId, status: 'APPROVED' });

  if (!pendingCommissions.length) {
    return next(new AppError('No pending commissions found for this partner.', 400));
  }

  const paidAt = new Date();
  const updatePromises = pendingCommissions.map(c => {
    c.status = 'PAID';
    c.payoutTxnId = payoutTxnId || `TXN-${Date.now()}`;
    c.paidAt = paidAt;
    if (notes) c.notes = notes;
    return c.save();
  });

  await Promise.all(updatePromises);

  res.status(200).json({
    status: 'success',
    message: `Successfully processed payout for ${pendingCommissions.length} commissions.`
  });
});
